services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: carrental
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
